### ISSUE TITLE
Contrato Final Proyecto

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/contrato-de-software-entrevista#1]
[Contrato de desarrollo de software FORMATO.pdf](https://github.com/SistemasTecTlaxiaco/contrato-de-software-entrevista/files/7740174/Contrato.de.desarrollo.de.software.FORMATO.pdf)

**Comment by EDITH-R** [comment]
Calificación: 20

**Comment by dulce-blm** [comment]
[Contrato de desarrollo de software FORMATO.pdf](https://github.com/SistemasTecTlaxiaco/contrato-de-software-entrevista/files/7740168/Contrato.de.desarrollo.de.software.FORMATO.pdf)

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
